# use Ganache's forked mainnet mode as the default network
networks:
  default: development

autofetch_sources: true

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.6.0

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    version: 0.8.20
    optimizer:
        runs: 200
        enabled: true
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0"

reports:
  exclude_paths:
    - contracts/test/Token.sol
  exclude_contracts:
    - SafeMath
    - SafeERC20
    - Address
wallets :
  from_key: ${PRIVATE_KEY}
  t_from_key : ${T_PRIVATE_KEY}
